require 'has_random_column'
require 'has_random_column/has_random_column'
require 'has_random_column/has_random_integer'
require 'has_random_column/has_random_primary_key'
require 'has_random_column/has_random_token'
require 'has_random_column/has_random_token_digest'
